DATA_DIR: "/scratch/peidli/scPerturb/"  # Directory where we will store the downloaded data from scperturb.org
OUT_DIR: "/home/peidli/projects/scPerturb/"  # Directory where the output of your method will be stored
DATASETS: "all"  # "all" or a list of dataset names in scperturb.org
ZENODO_RNA_URL: 'https://zenodo.org/record/10044268/'  # V1.3, RNA
ZENODO_ATAC_URL: 'https://zenodo.org/record/7058382' # V1.0 ATAC
